# herbal-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: herbal-backend-secrets
type: Opaque # Standard type for arbitrary user-defined data
data:
  # Base64 encoded values for sensitive environment variables
  # Replace these with your actual base64 encoded values
  GEMINI_API_KEY: QUl6YVN5RFUySVJYOHZqQTVkdEVmY3VKNklSQUt1djRJajFDQkw0 #AIzaSyDU2IRX8vjA5dtEfcuJ6IRAKuv4Ij1CBL4 # base64 encode your actual key
  POSTGRES_USER: ZGhhcnNoYW4= # base64 encode "dharshan"
  POSTGRES_PASSWORD: ZGhhcnNoYW4= # base64 encode "dharshan"
  POSTGRES_DB: UGxhbnRBV1M= # Base64 encoded "PlantAWS"
  POSTGRES_HOST: cGxhbnRzLWF3cy1pbnN0YW5jZS5jNmJpaXk0a3NqbDkudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t #plants-aws-instance.c6biiy4ksjl9.us-east-1.rds.amazonaws.com
  POSTGRES_PORT: NTQzMg== # base64 encode "5432"
