#  helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm repo update
# helm install ingress-nginx ingress-nginx/ingress-nginx   --namespace ingress-nginx   --create-namespace   --set controller.service.type=LoadBalancer
# helm install ingress-nginx ingress-nginx/ingress-nginx  --set controller.service.type=LoadBalancer

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: herbal-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false" 
    # Otherwise, for HTTPS, you'd configure cert-manager or manually provide a secret
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true" # Optional: Forces redirect HTTP to HTTPS
spec:
  ingressClassName: nginx # This is crucial to tell Nginx Ingress Controller to manage this Ingress
  rules:
  # - host: api.herbal-garden.com # <--- REPLACE WITH YOUR DESIRED API DOMAIN (e.g., api.yourdomain.com)
    - http:
       paths:
       - path: /
         pathType: Prefix # Catches all paths starting with /
         backend:
          service:
            name: {{ .Values.backend.service_name }} # Name of your backend ClusterIP service
            port:
              number: 8005 # Port your backend service exposes
