# herbal-garden-application/templates/alertmanager-email-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mail-pass
  namespace: monitoring # Must be in the same namespace as Alertmanager
type: Opaque
data:
  gmail-pass: cXJvZCBzdXl4IGdrd2MgdWxzYw==

  #cXJvZHN1eXhna3djdWxzYw==

