FROM python:3.10-slim-buster
WORKDIR /app
COPY . /app/server/
WORKDIR /app/server/
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /app
EXPOSE 8005
CMD ["python", "-m", "uvicorn", "server.main:app", "--host", "0.0.0.0", "--port", "8005", "--app-dir", "."]
